### ISSUE TITLE
Indigo install fails from rosinstall

### ISSUE THREAD

**Issue by bmagyar** [pal-robotics/tiago_tutorials#15]
With duplicated target name for `run_motion` which is defined both by `play_motion` and `run_motion` in this package. 

IMHO `play_motion` could simply be installed from debians, probably only needs bloom to be called on it (last indigo release was 4.1, current version is 4.4).

**Comment by jordi-pages** [comment]
@bmagyar the run_motion package is deprecated and has now been removed from indigo-devel branch of tiago_tutorials. Thanks.

**Comment by bmagyar** [comment]
Thank you!
