### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by olivier-stasse** [pal-robotics/tiago_tutorials#26]
Dear PAL team,
Thanks a lot for the great tutorials.
Would it be possible to release the current version ?
2.0.2 does not compile on melodic because it is missing the last commits.
Thanks again for your help.

Best regards,
Olivier.

**Comment by v-lopez** [comment]
Done, 2.0.3 is available now

**Comment by olivier-stasse** [comment]
Thanks a lot !
