### ISSUE TITLE
Tiago on ubuntu 20.04 and ros noetic

### ISSUE THREAD

**Issue by Gryogor** [pal-robotics/tiago_tutorials#36]
Hello.
I know that currently ROS noetic is not supported for running tiago, but after some branch checkouts and git clones I managed to "launch" tiago simulation, but there is the problem with SRDF parsing for moveit:

`[ERROR] [1633959912.422208296]: Could not parse the SRDF XML File. Error=XML_ERROR_PARSING_DECLARATION ErrorID=13 (0xd) Line number=2: XMLDeclaration value=xml version="1.0" `

and 

`[ERROR] [1633959912.422794852]: Unable to parse SRDF from parameter '/robot_description_semantic'`

Is there any idea what can cause it?

**Comment by nkvch** [comment]
Hi, did the problem resolve?

**Comment by sasilva1998** [comment]
Could anyone run Tiago robot simulation using noetic?

**Comment by saikishor** [comment]
Hello @sasilva1998,

Thank you for showing interest on our TIAGo. Regarding the noetic simulation, we are currently migrating to noetic and you could expect the update in upcoming weeks. In the meantime, you could use our TIAGo simulation via [Dockers](http://wiki.ros.org/Robots/TIAGo/Tutorials/Installation/Installing_Tiago_tutorial_docker).

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by sasilva1998** [comment]
Hi @saikishor thanks for your reponse.  In the end I could run all the TIAGO simulation successfully. I hadn't realized that I needed to use the gazebo packages forks from pal-robotics-forks, which honestly wasn't desired since it was to setup TIAGO simulation for a common environment with other robots.

**Comment by saikishor** [comment]
Hello @sasilva1998,

We are glad you could make it work.

Best Regards,
PAL Robotics Team.

**Comment by Juancams** [comment]
Hello,

i am having the same error. I am using the [ros1_bridge](https://github.com/Juancams/ros1_bridge/blob/dedicated_bridges_lifecycle/src/moveit_2_to_1.cpp) package and when I publish and enter the callback, when I call the group which I want to move, it tells me the following:

`[moveit_2_to_1-9] [ERROR] [1518026924.193459623]: Could not parse the SRDF XML File. Error=XML_ERROR_PARSING_DECLARATION ErrorID=13 (0xd) Line number=2: XMLDeclaration value=xml version="1.0" `

`[moveit_2_to_1-9] [ERROR] [1518026924.198702754]: Unable to parse SRDF from parameter '/robot_description_semantic'`

`[moveit_2_to_1-9] [ WARN] [1518026924.256199284]: Link base_laser_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [ WARN] [1518026924.256259188]: Link base_sonar_01_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [ WARN] [1518026924.256279294]: Link base_sonar_02_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [ WARN] [1518026924.256295976]: Link base_sonar_03_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [ WARN] [1518026924.256337513]: Link caster_back_left_1_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [ WARN] [1518026924.256446377]: Link caster_back_right_1_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [ WARN] [1518026924.256513612]: Link caster_front_left_1_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [ WARN] [1518026924.256563940]: Link caster_front_right_1_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [ WARN] [1518026924.300300539]: Link base_cover_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

`[moveit_2_to_1-9] [FATAL] [1518026924.411205856]: Group 'arm_torso' was not found.`

`[moveit_2_to_1-9] terminate called after throwing an instance of 'std::runtime_error'`

`[moveit_2_to_1-9]   what():  Group 'arm_torso' was not found.`

I have tried to modify the srdf.em and the tiago_pal-hey5_schunk-ft.srdf (default) by changing `<?xml version="1.0"?>` to `<?xml version="1.0" encoding=" UTF-8"?>` and it still doesn't work

**Comment by saikishor** [comment]
Hello @Juancams,

We are unable to reproduce the issue in a clear noetic docker. We will need some clear set of instructions and the environment you are using to reproduce it. We request you provide these instructions in order to help you with your issue.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by Juancams** [comment]
I have created a docker with ubuntu focal, in which ros noetic is installed, and compiled ros2 foxy. Use this [Dockerfile](https://github.com/Juancams/ros1_bridge/blob/dedicated_bridges_lifecycle/Dockerfile)

Once the image is created and loaded into tiago, go inside it, source from both distros and launch the ros1_bridge launcher. When trying to send a position through the topic /tiago_arm/goal, this error occurs.

I leave you here the command to enter in the same way as me: 
`sudo docker run -h bridge --network=host --add-host <hostname>:<ip -it -e ROS_MASTER_URI=http://<hostname>:11311/ -v /opt/pal/ferrum/share/tiago_description:/opt/ros/noetic/share/tiago_description -v /opt/pal/ferrum/share/pal_gripper_description:/opt/ros/noetic/share/pal_gripper_description -v /opt/pal/ferrum/share/pmb2_description:/opt/ros/noetic/share/pmb2_description -v /opt/pal/ferrum/share/tiago_moveit_config:/opt/ros/noetic/share/tiago_moveit_config -e ROS_IP=<IP> tiago_image`

**Comment by saikishor** [comment]
Hello @Juancams,

It could be that the ferrum version installed on your TIAGo should be too old and this could be causing the issues with your testing. This explains the issue you are facing.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by Juancams** [comment]
How can I update the Ferrum version of my tiago?

**Comment by saikishor** [comment]
Hello @Juancams,

> How can I update the Ferrum version of my tiago?

Please contact our [customer support system](https://support.pal-robotics.com) to get more information on it. 

Best Regards,
PAL Robotics Team.

**Comment by oscar-lima** [comment]
> Hello @sasilva1998,
> 
> Thank you for showing interest on our TIAGo. Regarding the noetic simulation, we are currently migrating to noetic and you could expect the update in upcoming weeks. In the meantime, you could use our TIAGo simulation via [Dockers](http://wiki.ros.org/Robots/TIAGo/Tutorials/Installation/Installing_Tiago_tutorial_docker).
> 
> Thank you,
> 
> Best Regards, PAL Robotics Team.

I was misled by this comment thinking that it referred to a kinetic-devel docker, to clarify this comment refers to a **noetic** docker available for tiago in simulation.
