### ISSUE TITLE
Question about Docker-based installation

### ISSUE THREAD

**Issue by famora2** [pal-robotics/tiago_tutorials#37]
I am trying to follow the docker-based installation. After following the last step, `rocker --home --user --nvidia --x11 palroboticssl/tiago_tutorials:melodic`, I am inside the docker container, but do I continue from here? 
Isn't a docker-compose.yml file missing file? Probably a simple step that I have missed...

**Comment by saikishor** [comment]
Hello @Joo236,

Thank you for showing interest in our TIAGo Simulation. Regarding your query with the docker container, yes once you are inside the docker container, you can continue working inside the container to use the simulation. You can start and stop the simulation in the container as you run in your own computer. In this case, `docker-compose.yaml` is not a necessity. 

We hope you enjoy using our TIAGo Simulation. In case of any queries, feel free to open an issue. 

Thank you,

Best Regards,
PAL Robotics Team.
