### ISSUE TITLE
error running ros2 launch tiago_gazebo tiago_gazebo.launch.py

### ISSUE THREAD

**Issue by AdrianCobo** [pal-robotics/tiago_tutorials#38]
# Type of bug
- [ ] A) Typo/error in Figure/text
- [X] B) Bug in code
- [ ] C) General comment, recommendation or petition 

# Issue Description
ros2 launch tiago_gazebo tiago_gazebo.launch.py not working

# A) *Typo/Error Description*
Waiting for '/controller_manager' node to exist
joy_teleop not working

## Screenshot
![Screenshot from 2022-10-06 18-55-29](https://user-images.githubusercontent.com/98641977/194373481-32ab2337-99bf-4b5a-931c-35656b562f0e.png)
![Screenshot from 2022-10-06 18-55-41](https://user-images.githubusercontent.com/98641977/194373487-92d79a1d-9d32-4c65-8243-a53e7fecb064.png)
![Screenshot from 2022-10-06 18-55-53](https://user-images.githubusercontent.com/98641977/194373489-4b8c3c48-3191-4517-9d48-305126d50eec.png)
![Screenshot from 2022-10-06 18-55-59](https://user-images.githubusercontent.com/98641977/194373490-16a6c6bd-419b-4e99-8ec0-11bac44ac516.png)

## how to reproduce
1. run in a terminal: ros2 launch br2_tiago sim.launch.py

## Desktop :
 - OS: [Ubuntu 22.04]
 - ROS2 Distro [Humble]

**Comment by saikishor** [comment]
Hello @AdrianCobo,

We are preparing a readme file with more detailed instructions that we will made them available soon.

First of all, I recommend you change to Cyclone DDS. With the Fast-DDS we are having some issues, similar that the one you reported. You can do it by setting an environment variable with the command export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp.

Then you can use the [tiago_public.rosinstall](https://github.com/pal-robotics/tiago_tutorials/blob/humble-devel/tiago_public.rosinstall) to get all the packages needed for TIAGo simulation. 

Finally, you can launch the simulation with the command you've been using `ros2 launch tiago_gazebo tiago_gazebo.launch.py`

Best Regards,
PAL Robotics Team.

**Comment by AdrianCobo** [comment]
okay, thanks. 

How i have to use the [tiago_public.rosinstall](https://github.com/pal-robotics/tiago_tutorials/blob/humble-devel/tiago_public.rosinstall) ? Sorry for the question but i have never used it before.

Have a nice day,
Adrián

**Comment by saikishor** [comment]
Hello @AdrianCobo,

You can refer to this page for more info: http://wiki.ros.org/vcstool.

We hope this helps. We are looking forward for you to use our TIAGo simulation in ROS2.

Best Regards,
PAL Robotics Team.

**Comment by AdrianCobo** [comment]
thanks, 
but now I am getting this error executing ros2 launch tiago_gazebo tiago_gazebo.launch.py:
1665090451.7330711 [INFO] [launch]: All log files can be found below /home/adrian/.ros/log/2022-10-06-23-07-31-732528-PORTATIL-18169
1665090451.7332942 [INFO] [launch]: Default logging verbosity is set to INFO
1665090451.9130342 [ERROR] [launch]: Caught exception in launch (see debug for traceback): No module named 'launch_param_builder'

Thanks for all your help,
Adrian

**Comment by saikishor** [comment]
Hello @AdrianCobo,

You are missing to install the package [launch_param_builder](https://github.com/PickNikRobotics/launch_param_builder). Please try to install the package or install all dependencies using rosdep. We hope this helps to solve your issue.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by AdrianCobo** [comment]
All done but now i am getting the same initial issue

![Screenshot from 2022-10-07 10-18-12](https://user-images.githubusercontent.com/98641977/194507773-f87a68a6-c5ed-4b0a-9b79-e43aede61f72.png)
![Screenshot from 2022-10-07 10-18-37](https://user-images.githubusercontent.com/98641977/194507776-f577730f-f3a3-4880-a32c-ec35c35f8153.png)
![Screenshot from 2022-10-07 10-18-46](https://user-images.githubusercontent.com/98641977/194507780-a6730db3-4f5c-4dea-a892-b723f62127c9.png)
![Screenshot from 2022-10-07 10-18-57](https://user-images.githubusercontent.com/98641977/194507782-7deae61f-1c8b-4e28-92ac-148d3337f937.png)
![Screenshot from 2022-10-07 10-19-51](https://user-images.githubusercontent.com/98641977/194507785-48aa4048-e5d6-4a25-b45f-b85004e3c8bc.png)
![Screenshot from 2022-10-07 10-20-16](https://user-images.githubusercontent.com/98641977/194507789-e9419473-d216-4439-8525-293143c2cce2.png)
![Screenshot from 2022-10-07 10-20-24](https://user-images.githubusercontent.com/98641977/194507791-0e3e712f-9993-4533-b6cf-bf4b075e68a2.png)
![Screenshot from 2022-10-07 10-20-40](https://user-images.githubusercontent.com/98641977/194507793-955a15f7-dffa-4cb1-a8fc-db0115d381ac.png)

**Comment by Noel215** [comment]
Hi @AdrianCobo, 

Execute `dpkg -l | grep humble | grep control`. I think you could be missing `ros-humble-gazebo-ros2-control` package.
If not, try to clean your workspace and be sure that you are using Cyclone DDS.

For the next time, it's better for us that you paste the log instead of screenshots because it's easier to parse.

**Comment by AdrianCobo** [comment]
oh sorry,
yeh you were right, that package was missing but I installed it and now the simulation is correctly working!!!

But  now i have other problem; the robot does not move using:
-ros2 launch tiago_gazebo tiago_gazebo.launch.py world_name:=factory
                                     or
-ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -r cmd_vel:=key_vel

:( 

Thank you so much for all the help!!!

**Comment by saikishor** [comment]
Hello @AdrianCobo,

We are glad that it worked. Regarding the velocity, try to publish the velocity using the command line and see if you can publish. The topic to publish is `/mobile_base_controller/cmd_vel_unstamped`. We hope this helps.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by AdrianCobo** [comment]
yea, i can publish but it dosnt move.

Now i see that i am getting this error:

[gzserver-1] [ERROR] [1665143870.690903681] [controller_manager]: The 'type' param was not defined for 'torso_controller'.
[ERROR] [spawner-7]: process has died [pid 4697, exit code 1, cmd '/home/adrian/Escritorio/tiagosim_ws/install/controller_manager/lib/controller_manager/spawner torso_controller --controller-manager controller_manager --controller-type joint_trajectory_controller/JointTrajectoryController --param-file /home/adrian/Escritorio/tiagosim_ws/install/tiago_controller_configuration/share/tiago_controller_configuration/config/torso_controller.yaml --ros-args'].

**Comment by AdrianCobo** [comment]
Yeh it works using ros2 topic pub -r 10 /mobile_base_controller/cmd_vel_unstamped geometry_msgs/Twist "linear: {x: 0.3}"

Thank you for all!!!

**Comment by saikishor** [comment]
Hello @AdrianCobo,

We are glad you could work it out.

Best Regards,
PAL Robotics Team.
