### ISSUE TITLE
gazebo simulation not working properly

### ISSUE THREAD

**Issue by hawraaxcx** [pal-robotics/tiago_tutorials#39]
when I run gazebo --verbose, I encounter this error:

[Wrn] [GuiIface.cc:120] QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000', please create it with 0700 permissions.
dbus[63253]: D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text)
  D-Bus not built with -rdynamic so unable to print a backtrace

what should I do to fix it?

**Comment by saikishor** [comment]
Hello @hawraaxcx,

Thank you for showing interest in our TIAGo simulation. We are sorry to know that you are unable to run the simulation. We have cross checked on our end, the simulation runs successfully across various machines with different configurations. I recommend you to crosscheck your system configuration and setup to fix the issue running Gazebo simulation. 

Thank you,  

Best Regards,
PAL Robotics Team.
