### ISSUE TITLE
Moving from tutorial to real robot.

### ISSUE THREAD

**Issue by Skevinci** [pal-robotics/tiago_tutorials#43]
Hi there,
After reading all these tutorials, I find them really helpful. But when I decide to move from tutorial, from the simulation environment to the real world robot, I become a little confused sometimes. I'm wondering if all those nodes and topics are already included in the ROS of robot or I need to copy the tutorial's workspace to the robot? Since the size of the tutorial's workspace is quite large and using scp command to copy the tutorial's workspace to the robot needs quite a lot of time, moreover, when I consider just copying the packages I want, there are actually many interations between different packages so that it doesn't work. Is there any advice to better achieve tutorial's goal in the real world?
Thank you very much!

**Comment by saikishor** [comment]
Hello @Skevinci,

Thank you for showing your interest. Regarding your query, the tutorials are just to show the functionality of the robot and the interfaces it can provide. For instance, MoveIt, Camera, and other mobile base and navigation interfaces. It's most probable that this part of the code doesn't exist on the robot, as these are meant to be used as a reference for your use cases. However, you can deploy most of them inside the robot and run them, if you want to test them (or) export the ROS_MASTER_URI of your robot and then run these from your machine itself.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by Skevinci** [comment]
Thank you very much！
