### ISSUE TITLE
tiago_bringup: Cannot locate rosdep definition for [pal_motion_loader]

### ISSUE THREAD

**Issue by bach05** [pal-robotics/tiago_tutorials#44]
I followed the instructions from the [official wiki](https://wiki.ros.org/Robots/TIAGo/Tutorials/Installation/InstallUbuntuAndROS) until: 

`rosdep install -y --from-paths src --ignore-src --rosdistro noetic --skip-keys "urdf_test omni_drive_controller orocos_kdl pal_filters libgazebo9-dev pal_usb_utils speed_limit_node camera_calibration_files pal_moveit_plugins pal_startup_msgs pal_local_joint_control pal_pcl_points_throttle_and_filter current_limit_controller hokuyo_node dynamixel_cpp pal_moveit_capabilities pal_pcl dynamic_footprint gravity_compensation_controller pal-orbbec-openni2 pal_loc_measure pal_map_manager ydlidar_ros_driver"`

But I get this error: 
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tiago_bringup: Cannot locate rosdep definition for [pal_motion_loader]
```
I am running on Ubuntu 20.04, ROS Noetic 1.16.0.

**Comment by saikishor** [comment]
Hello @bach05!

This is already solved. Sorry for reaching out this late.

Thank you,

Best Regards,
PAL Robotics Team
