### ISSUE TITLE
TIAGo hitting objects in simulation

### ISSUE THREAD

**Issue by ah96** [pal-robotics/tiago_tutorials#45]
When running "Localization and path planning" tutorial with both ROS Noetic and Melodic, TIAGo keep hitting obstacles during navigation. When it gets stuck at big obstacle such as part of wall, it cannot proceed. Global path planning work good. Any local planner available fails to produce good plans.

**Comment by AntoBrandi** [comment]
Hi @ah96,
Thank you for showing interest in our TIAGo simulation. We have tried to reproduce your issue but unable to do so, we would need more information to reproduce it on our end. We also recommend you to take a look at our [Public Simulation Dockers](http://wiki.ros.org/Robots/TIAGo/Tutorials/Installation/Installing_Tiago_tutorial_docker) for your use.

Thank you,

Best Regards,
PAL Robotics Team.
