### ISSUE TITLE
rosdep install error

### ISSUE THREAD

**Issue by jacknlliu** [pal-robotics/tiago_tutorials#9]
I follow the [Installing TIAGo Simulation](http://wiki.ros.org/Robots/TIAGo/Tutorials/Installation/TiagoSimulation), but when I run the following command, I got errors.
```sh
$ rosdep install --from-paths src --ignore-src --rosdistro indigo --skip-keys="opencv2 opencv2-nonfree pal_laser_filters speed_limit sensor_to_cloud"

dpkg-query: no packages found matching ros-indigo-sick-tim
dpkg-query: no packages found matching ros-indigo-humanoid-nav-msgs
dpkg-query: no packages found matching ros-indigo-hokuyo-node
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pmb2_simulation: Cannot locate rosdep definition for [pmb2_2dnav_gazebo]
```

Any help will be  appreciated!

**Comment by v-lopez** [comment]
Hi @jacknlliu thanks for noticing it, we removed that dependency since it wasn't being used. Pulling the latest changes from https://github.com/pal-robotics/pmb2_simulation should solve your issue.
